# base image
FROM alpine:latest

# MAINTAINER
MAINTAINER yygfml<yygfml@163.com>
  
# put vlmcsd into /usr/local/bin
ADD vlmcsd /usr/local/bin
  
# execute command to compile vlmcsd
CMD vlmcsd -L 0.0.0.0:1688 -e -D
EXPOSE 1688
